apiVersion: v1	
kind: Service	
metadata:	
  name: web-skp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: leap.fhcdan.net
  namespace: www
spec:
  type: LoadBalancer
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    run: web-skp
